### PR TITLE
Fix AWS ControlPlane controller shoot delete flow

### LINKED ISSUE #233: Control plane exposure controller
We have introduced a `ControlPlane` CRD whose `spec` contains a `type` field for the respective shoot provider. It's purpose is to install any provider-specific components into the seed (or shoot) that are required to make the cluster functional. Examples of those components are the cloud-controller-manager, CSI controllers/plugins, or storage classes.

Some providers have additional needs: They might need to deploy components that are required to expose the control plane. The kube-apiserver of a shoot is exposed via a load balancer in the seed. The seed provider might be different from the shoot provider (for example, you can create an AWS shoot whose control plane is running on a GCP seed). Examples for those components are the [`aws-lb-readvertiser`](https://github.com/gardener/aws-lb-readvertiser). While most seed providers don't need to do anything here some might have this requirement.

The plan is to enhance the current `ControlPlane` resource (instead of creating an entirely new CRD named `ControlPlaneExposure`). Let's introduce a new `.spec.purpose` field whose possible values are `{exposure,normal}` (naming suggestions/improvements are welcome):

```yaml
apiVersion: extensions.gardener.cloud/v1alpha1
kind: ControlPlane
metadata:
  ...
spec:
  type: aws
  purpose: exposure
  ...
```

When seeing such a resource the AWS control plane exposure controller shall deploy the `aws-lb-readvertiser`.

The resource doesn't need to have any infrastructure information (because the infrastructure is created for the shoot cloud provider).

### PR DESCRIPTION
**Pull request by svetlinas**
**What this PR does / why we need it**:
Currently AWS provider controller is failing during shoot deletion because of not fully descriptive  Unstructured object in one of the chart definitions. This Unstructured object needs to represent  VerticalPodAutoscaler. 
The PR is also adding Unstructured objects to all of the charts which contain VerticalPodAutoscalers in order for these objects to be specifically deleted during shoot deletion.

**Which issue(s) this PR fixes**:
Fixes #233 

**Release note**:

```improvement operator
Fix AWS ControlPlane controller shoot delete flow
```

### CODE REVIEW

File: controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go [hunk 1]
```diff
@@ -292,3 +293,10 @@ func getCCMChartValues(
 
 	return values, nil
 }
+
+// getVerticalPodAutoscalerObject returns Unstructured object describing VerticalPodAutoscaler of group "autoscaling.k8s.io"
+func getVerticalPodAutoscalerObject() *unstructured.Unstructured {
+	obj := &unstructured.Unstructured{}
+	obj.SetGroupVersionKind(schema.GroupVersionKind{Group: "autoscaling.k8s.io", Kind: "VerticalPodAutoscaler", Version: "v1beta2"})
```
Comment (timuthy) [inline controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go]: Can you try to reuse `SchemeGroupVersion` from https://github.com/kubernetes/autoscaler/blob/5ff9f7b8ba65cfec027da647aff79f63c1176fbe/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/register.go#L26?

Comment (svetlinas) [reply controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go]: I tried, but I cannot make gardener-extensions to depend on this project, I cannot build the correct project:version
